
# vocab
PAD_TOKEN = '<PAD>'
PAD_ID = 0
UNK_TOKEN = '<UNK>'
UNK_ID = 1


TREEMATCH_LABEL = [0, 1]


INFINITY_NUMBER = 1e12


DEPREL_TO_ID = {PAD_TOKEN: 0,
                UNK_TOKEN: 1,
                'acl': 2,
                'acl:relcl': 3,
                'acomp': 4,
                'advcl': 5,
                'advmod': 6,
                'amod': 7,
                'appos': 8,
                'aux': 9,
                'auxpass': 10,
                'aux:pass': 10,
                'case': 11,
                'cc': 12,
                'cc:preconj': 13,
                'ccomp': 14,
                'compound': 15,
                'compound:prt': 16,
                'conj': 17,
                'cop': 18,
                'csubj': 19,
                'csubjpass': 20,
                'csubj:pass': 20,
                'dep': 21,
                'det': 22,
                'det:predet': 23,
                'discourse': 24,
                'dobj': 25,
                'erased': 26,
                'expl': 27,
                'iobj': 28,
                'mark': 29,
                'mwe': 30,
                'neg': 31,
                'nmod': 32,
                'nmod:npmod': 33,
                'nmod:poss': 34,
                'nmod:tmod': 35,
                'nn': 36,
                'npadvmod': 37,
                'nsubj': 38,
                'nsubjpass': 39,
                'nsubj:pass': 39,
                'num': 40,
                'number': 41,
                'nummod': 42,
                'parataxis': 43,
                'pcomp': 44,
                'pobj': 45,
                'poss': 46,
                'possessive': 47,
                'preconj': 48,
                'predet': 49,
                'prep': 50,
                'prt': 51,
                'punct': 52,
                'quantmod': 53,
                'rcmod': 54,
                'root': 55,
                'tmod': 56,
                'vmod': 57,
                'xcomp': 58,
                'fixed': 59,
                'obj': 60,
                'obl': 61,
                'obl:npmod': 62,
                'obl:tmod': 63,
                'orphan': 64,
                'flat': 65,
                'list': 66,
                'vocative': 67,
                'reparandum': 68,
                'goeswith': 69,
                'flat:foreign': 70,
                'subtokens': 71,
                'special_rel': 72}


UDEPREL_TO_ID = {PAD_TOKEN: 0,
                 UNK_TOKEN: 1,
                 'acl': 2,
                 'advcl': 3,
                 'advmod': 4,
                 'amod': 5,
                 'appos': 6,
                 'aux': 7,
                 'case': 8,
                 'cc': 9,
                 'ccomp': 10,
                 'clf': 11,
                 'compound': 12,
                 'conj': 13,
                 'cop': 14,
                 'csubj': 15,
                 'dep': 16,
                 'det': 17,
                 'discourse': 18,
                 'dislocated': 19,
                 'expl': 20,
                 'fixed': 21,
                 'flat': 22,
                 'goeswith': 23,
                 'iobj': 24,
                 'list': 25,
                 'mark': 26,
                 'nmod': 27,
                 'nsubj': 28,
                 'nummod': 29,
                 'obj': 30,
                 'obl': 31,
                 'orphan': 32,
                 'parataxis': 33,
                 'punct': 34,
                 'reparandum': 35,
                 'root': 36,
                 'vocative': 37,
                 'xcomp': 38,
                 'subtokens': 39,
                 'special_rel': 40
                 }

